# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'y2mp3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from __future__ import unicode_literals
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog,QLabel
from PyQt5.QtGui import QIcon
from bs4 import BeautifulSoup
import requests
import datetime
import youtube_dl
import urllib.request
import os
import pyperclip
import pafy

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 538)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_4.addWidget(self.label_37)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 1, 1, 7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 3, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_9.addWidget(self.label_29)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_9.addWidget(self.label_34)
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_9.addWidget(self.label_39)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_8, 7, 1, 1, 7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_11.addWidget(self.label_35)
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_11.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_11.addWidget(self.label_41)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.verticalLayout_10, 8, 1, 1, 7)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setScaledContents(False)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.label_31)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_2.addWidget(self.label_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 1, 1, 7)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_6.addWidget(self.toolButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 8, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 4, 8, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_7.addWidget(self.label_38)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_6, 6, 1, 1, 7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_3.addWidget(self.lineEdit_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 5, 8, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_5.addWidget(self.toolButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_5, 6, 8, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_8.addWidget(self.lineEdit_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_8.addWidget(self.toolButton_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_7, 7, 8, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_9.addWidget(self.pushButton_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_10.addWidget(self.toolButton_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_9, 8, 8, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 4, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.pushButton_6.clicked.connect(self.lineEdit.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_4.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_5.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_6.clear)
        self.pushButton_6.clicked.connect(self.lineEdit_7.clear)
        self.pushButton_6.clicked.connect(self.reset)
        self.pushButton_7.clicked.connect(self.ytmp3)
        self.toolButton_2.clicked.connect(lambda:self.copy(self.lineEdit_3.text()))
        self.toolButton_3.clicked.connect(lambda:self.copy(self.lineEdit_4.text()))
        self.toolButton_4.clicked.connect(lambda:self.copy(self.lineEdit_5.text()))
        self.toolButton_5.clicked.connect(lambda:self.copy(self.lineEdit_6.text()))
        self.toolButton_6.clicked.connect(lambda:self.copy(self.lineEdit_7.text()))
        self.pushButton.clicked.connect(lambda:self.download(self.lineEdit_3.text()))
        self.pushButton_2.clicked.connect(lambda:self.download(self.lineEdit_4.text()))
        self.pushButton_3.clicked.connect(lambda:self.download(self.lineEdit_5.text()))
        self.pushButton_4.clicked.connect(lambda:self.download(self.lineEdit_6.text()))
        self.pushButton_5.clicked.connect(lambda:self.download(self.lineEdit_7.text()))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube to Mp3"))
        self.label_7.setText(_translate("MainWindow", "Title of the Song"))
        self.label_8.setText(_translate("MainWindow", "Channel Name"))
        self.label_23.setText(_translate("MainWindow", "views"))
        self.label_27.setText(_translate("MainWindow", "Likes"))
        self.label_32.setText(_translate("MainWindow", "Duration"))
        self.label_37.setText(_translate("MainWindow", "published at"))
        self.pushButton_6.setText(_translate("MainWindow", "Reset"))
        self.pushButton_7.setText(_translate("MainWindow", "Search"))
        self.label_13.setText(_translate("MainWindow", "Title of the Song"))
        self.label_14.setText(_translate("MainWindow", "Channel Name"))
        self.label_25.setText(_translate("MainWindow", "views"))
        self.label_29.setText(_translate("MainWindow", "Likes"))
        self.label_34.setText(_translate("MainWindow", "Duration"))
        self.label_39.setText(_translate("MainWindow", "published at"))
        self.label_16.setText(_translate("MainWindow", "Title of the Song"))
        self.label_17.setText(_translate("MainWindow", "Channel Name"))
        self.label_30.setText(_translate("MainWindow", "views"))
        self.label_35.setText(_translate("MainWindow", "Likes"))
        self.label_40.setText(_translate("MainWindow", "Duration"))
        self.label_41.setText(_translate("MainWindow", "published at"))
        self.label_2.setText(_translate("MainWindow", "name"))
        self.label_19.setText(_translate("MainWindow", "                                                     "))
        self.label_9.setText(_translate("MainWindow", "photo"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search The name of the song"))
        self.label_12.setText(_translate("MainWindow", "photo"))
        self.label_21.setText(_translate("MainWindow", "Destination"))
        self.label_15.setText(_translate("MainWindow", "photo"))
        self.label_18.setText(_translate("MainWindow", "photo"))
        self.label_4.setText(_translate("MainWindow", "photo"))
        self.label_5.setText(_translate("MainWindow", "Title of the Song"))
        self.label_6.setText(_translate("MainWindow", "Channel Name"))
        self.label_22.setText(_translate("MainWindow", "views"))
        self.label_26.setText(_translate("MainWindow", "Likes"))
        self.label_31.setText(_translate("MainWindow", "Duration"))
        self.label_36.setText(_translate("MainWindow", "published at"))
        self.label.setText(_translate("MainWindow", "Youtube to Mp3 Converter"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "C:\\Users\\Public\\Downloads"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/results?search_query=abcdefghijklmnopqrstuvwxyz"))
        self.toolButton_2.setText(_translate("MainWindow", "∾"))
        self.label_10.setText(_translate("MainWindow", "Title of the Song"))
        self.label_11.setText(_translate("MainWindow", "Channel Name"))
        self.label_24.setText(_translate("MainWindow", "views"))
        self.label_28.setText(_translate("MainWindow", "Likes"))
        self.label_33.setText(_translate("MainWindow", "Duration"))
        self.label_38.setText(_translate("MainWindow", "published at"))
        self.pushButton_2.setText(_translate("MainWindow", "Download"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/results?search_query=abcdefghijklmnopqrstuvwxyz"))
        self.toolButton_3.setText(_translate("MainWindow", "∾"))
        self.pushButton_3.setText(_translate("MainWindow", "Download"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/results?search_query=abcdefghijklmnopqrstuvwxyz"))
        self.toolButton_4.setText(_translate("MainWindow", "∾"))
        self.pushButton_4.setText(_translate("MainWindow", "Download"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/results?search_query=abcdefghijklmnopqrstuvwxyz"))
        self.toolButton_5.setText(_translate("MainWindow", "∾"))
        self.pushButton_5.setText(_translate("MainWindow", "Download"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/results?search_query=abcdefghijklmnopqrstuvwxyz"))
        self.toolButton_6.setText(_translate("MainWindow", "∾"))
        self.label_20.setText(_translate("MainWindow", "Results"))
        self.toolButton.clicked.connect(self.selectFile)
        

    def show_image(self,label,url):
        
        data = urllib.request.urlopen(url).read()

        image = QtGui.QImage()
        image.loadFromData(data)
        label.setPixmap(QtGui.QPixmap(image))

    def reset(self):
        self.label_5.setText("Title of the Song")
        self.label_7.setText("Title of the Song")
        self.label_10.setText("Title of the Song")
        self.label_13.setText("Title of the Song")
        self.label_16.setText("Title of the Song")
        self.label_4.setText("photo")
        self.label_9.setText("photo")
        self.label_12.setText("photo")
        self.label_15.setText("photo")
        self.label_18.setText("photo")
        self.label_6.setText("Channel Name")
        self.label_8.setText("Channel Name")
        self.label_11.setText("Channel Name")
        self.label_14.setText("Channel Name")
        self.label_17.setText("Channel Name")
        self.label_22.setText("views")
        self.label_23.setText("views")
        self.label_24.setText("views")
        self.label_25.setText("views")
        self.label_30.setText("views")
        self.label_26.setText("Likes")
        self.label_27.setText("Likes")
        self.label_28.setText("Likes")
        self.label_29.setText("Likes")
        self.label_35.setText("Likes")
        self.label_31.setText("Duration")
        self.label_32.setText("Duration")
        self.label_33.setText("Duration")
        self.label_34.setText("Duration")
        self.label_40.setText("Duration")
        self.label_36.setText("published at")
        self.label_37.setText("published at")
        self.label_38.setText("published at")
        self.label_39.setText("published at")
        self.label_41.setText("published at")

    def set(self,title,channel_name,views,likes,duration,published,link,thumb):
        self.label_5.setText(title[0])
        self.label_7.setText(title[1])
        self.label_10.setText(title[2])
        self.label_13.setText(title[3])
        self.label_16.setText(title[4])
        self.show_image(self.label_4,thumb[0])
        self.show_image(self.label_9,thumb[1])
        self.show_image(self.label_12,thumb[2])
        self.show_image(self.label_15,thumb[3])
        self.show_image(self.label_18,thumb[4])
        self.label_6.setText(channel_name[0])
        self.label_8.setText(channel_name[1])
        self.label_11.setText(channel_name[2])
        self.label_14.setText(channel_name[3])
        self.label_17.setText(channel_name[4])
        self.label_22.setText(str(views[0]))
        self.label_23.setText(str(views[1]))
        self.label_24.setText(str(views[2]))
        self.label_25.setText(str(views[3]))
        self.label_30.setText(str(views[4]))
        self.label_26.setText(str(likes[0]))
        self.label_27.setText(str(likes[1]))
        self.label_28.setText(str(likes[2]))
        self.label_29.setText(str(likes[3]))
        self.label_35.setText(str(likes[4]))
        self.label_31.setText(str(duration[0]))
        self.label_32.setText(str(duration[1]))
        self.label_33.setText(str(duration[2]))
        self.label_34.setText(str(duration[3]))
        self.label_40.setText(str(duration[4]))
        self.label_36.setText(published[0])
        self.label_37.setText(published[1])
        self.label_38.setText(published[2])
        self.label_39.setText(published[3])
        self.label_41.setText(published[4])
        self.lineEdit_3.setText(link[0])
        self.lineEdit_4.setText(link[1])
        self.lineEdit_5.setText(link[2])
        self.lineEdit_6.setText(link[3])
        self.lineEdit_7.setText(link[4])

    def selectFile(self):
        fname = QFileDialog.getExistingDirectory()
        self.lineEdit_2.setText(fname)

    def copy(self,lineEdit_1):
        if lineEdit_1 =="":
            self.showdlg("please search a song first")
            return
        pyperclip.copy(str(lineEdit_1))
        self.showdlg("link added to clip board")

    def date_set(self,lis):
        lis1=[]
        for i in lis:
            
            year=i[:4]
            month=i[4:6]
            day=i[6:]
            lis1.append(day+'-'+month+'-'+year)
        return lis1

    def time_set(self,lis):
        lis1=[]
        for i in lis:
            time=int(i)
            minute =time//60
            second =time%60
            lis1.append(str(minute)+':'+str(second))
        return lis1

    def showdlg(self,msg):
        Dialog=QtWidgets.QMessageBox()
        Dialog.setText(msg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowTitle("Youtube to Mp3")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        ret=Dialog.exec()

    def ytmp3(self):
        if self.lineEdit.text() =="":
            self.showdlg("Enter the link")
            return
        if self.lineEdit_2.text() =="":
            self.showdlg("Select the Destination")
            return
        
        os.chdir(self.lineEdit_2.text())
        self.link=[]
        self.title=[]
        self.duration=[]
        self.views=[]
        self.channel_name=[]
        self.likes=[] 
        self.published=[]
        self.thumb=[]
        i=0
        
        text= self.lineEdit.text()   
        query = urllib.parse.quote(text)
        url = "https://www.youtube.com/results?search_query=" + query
        response = urllib.request.urlopen(url)
        html = response.read()
        response.close()
        soup = BeautifulSoup(html, 'html.parser')
         
        for vid in soup.findAll(attrs={'class':'yt-uix-tile-link'}):
            if i<5:
                i+=1   
                temp = 'https://www.youtube.com' + vid['href']
                self.link.append(temp)
                self.thumb.append('http://img.youtube.com/vi/'+vid['href'].replace('/watch?v=','')+'/default.jpg')


                options = {
            'format': 'bestaudio/best', # choice of quality
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '320',
                }],
            'extractaudio' : True,      # only keep the audio
            'audioformat' : "mp3",      # convert to mp3 
             
            }
                with youtube_dl.YoutubeDL(options) as ydl:
                    
                    info_dict = ydl.extract_info(temp, download=False)
                    self.title.append(info_dict.get('title', None))
                    self.channel_name.append(info_dict.get('uploader', None))
                    self.published.append(info_dict.get('upload_date', None))
                    self.views.append(info_dict.get('view_count',None))
                    self.likes.append(info_dict.get('like_count',None))
                    self.duration.append(info_dict.get('duration',None))


            else:
                break

                
        self.set(self.title,self.channel_name,self.views,self.likes,self.time_set(self.duration),self.date_set(self.published),self.link,self.thumb)
            
       


    def download(self,lineEdit_1):
        text= lineEdit_1
        if text =='':
            self.showdlg("please search a song first")
            return
        print(text)
        options = {
            'format': 'bestaudio/best', # choice of quality
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '320',
                }],
            'extractaudio' : True,      # only keep the audio
            'audioformat' : "mp3",      # convert to mp3 
               
            }
        with youtube_dl.YoutubeDL(options) as ydl:
            ydl.download([text])
            self.showdlg("Downloaded at "+ os.getcwd())
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

